### PR TITLE
Add non-panicking variants of the functions.

### PR DESCRIPTION
**Pull request by marmistrz**
While it's true that `CLOCK_PROCESS_CPUTIME_ID` on Linux has been there for very long, but for other nixes the support is much more recent and was added in 2013 for both [OpenBSD](https://github.com/openbsd/src/commit/7b36c281ba1c99d528efca950572c207acd2e184) and [FreeBSD](https://github.com/freebsd/freebsd/commit/e8cf8aab231fe1b1ae82eff6e64af146514eea71). On OSX `clock_gettime` is unsupported [before Sierra (2016)](http://www.manpagez.com/man/3/clock_gettime/)

I'm not really sure about Windows, but as far as I understand, this function may fail depending on the security/privilege configuration and how the process/thread was created, see [this MSDN page](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreadtimes)

I also ran `rustfmt` on the parts of the code changed by me. You may consider reformatting the whole tree using `rustfmt` and adding the style check to the CI.

### CODE REVIEW

**Comment by tailhook** [comment]
Hello! Thanks for PR, but I do not agree.

The only sane usage for this API would be `ProcessTime::now().expect("CPU timer works")`. Which is super ugly and requires everybody invent their own text for panic (yes `unwrap()` is even worse).

So if you really want this add a separate constructor or `ProcessTime::is_supported()`.

Do you have some real use case in mind?

**Comment by marmistrz** [comment]
I don't know very much about Windows programming, but the permission failure sounds like a real thing to me. In principle libraries should not panic unless for bugs. We could possibly go for two set of functions, such as `try_now` and `try_elapsed` if you insist on this panicky behavior.

For the use case, see https://github.com/CraneStation/wasi-common/pull/119.

**Comment by marmistrz** [comment]
@tailhook ping...

**Comment by tailhook** [comment]
Sorry for long delay.

1. Yes, I'm okay with `try_now` and `try_elapsed`. I don't believe that permission issue on windows is something expected too often (i.e. will be only on specially sandboxed threads or somesuch, so most apps shouldn't care)
2. Also `cvt` crate is superfluous here. We already have different code paths on each platform. Just using current `if` statements to return result instead of panic is okay.

**Comment by marmistrz** [comment]
I dislike those panics, but you're the crate owner here. Panics make it more difficult to write robust code and libraries [should panic only in case of a bug, either in the library itself or in the user code](https://www.reddit.com/r/rust/comments/9x17hn/when_should_a_library_panic_vs_return_result/). This is neither case.

I added `try_now` and `try_elapsed` on Unix, let me know what you think. I'll make similar changes in the Windows implementation soon.

`cvt` is needed to be able to cleanly return an `io::Result`. Otherwise I'd just have to copy-paste the code from the crate and manually call `io::error::last_os_error`

**Comment by tailhook** [comment]
Looks good. Waiting for windows and cvt removal.

> Panics make it more difficult to write robust code

Most of the time, yes, but there are few use cases where consistent panic message for thing that never happens in practice is better. For example, `env_logger::init` just to name one of the very popular library.

> cvt is needed to be able to cleanly return an io::Result. Otherwise I'd just have to copy-paste the code from the crate and manually call io::error::last_os_error

Yes, just a call of last_os_error in two places doesn't leverage another dependency.

**Comment by marmistrz** [comment]
Windows support done.

> Yes, just a call of last_os_error in two places doesn't leverage another dependency.

First of all, not two but four. Moreover, moving common patterns to separate crates has numerous advantages:
1. It reduces the compilation time and, as a consequence, the energy used. If multiple crates are using the same version of the crate as a dependency, it can be reused between them. Moreover, the compilation result may be cached using `sccache`. Besides, this code will be rarely changed (if ever), so rustc won't have recompile this part of code every time you change anything inside `cpu-time`.
2. It reduces the code repetition, making the code clearer and less error-prone. Do you remember by heart what the return code conventions on various platforms are? I don't. It's also more difficult to forget to check the exit code when the compiler reminds you about the unused results.
3. The `cvt` crate is really minimal and will not bloat the resulting binary. Go and see the source yourself!

**Comment by tailhook** [comment]
> First of all, not two but four. Moreover, moving common patterns to separate crates has numerous advantages:

Yes, but not in this case. The compiler still needs to expand generics and there is still the overhead of the crate. Yes, I've inspected the code of the crate previously. And yes, conventions of the platform are already encoded in the original code anyway.

All in all, do you want to do this, or should I do it myself?

**Comment by marmistrz** [comment]
If you insist, I can remove the dependency on cvt, but I dislike the solution. I don't want to spend a load of time on this PR, anyway.

**Comment by marmistrz** [comment]
Done.

**Comment by tailhook** [comment]
Squash-merged in 7c955ec. Thanks! Sorry that it took so long...

**Comment by tailhook** [comment]
Released as v1.0.0

**Pull request closed without merging**
